steps:
- name: maven:3.6.0-jdk-11-slim
  entrypoint: 'mvn'
  args: ['clean', 'package', '-DskipTests']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/iwa_java:latest', '-t', 'gcr.io/$PROJECT_ID/iwa_java:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/iwa_java:$BUILD_ID', '.']
  id: 'build-image-IWAJava'

- name: 'fortifydocker/fortify-ci-tools:latest'
  entrypoint: bash
  args: 
    - -c
    - |
       fod_api_url='https://api.'`echo "$$FOD_BASEURL" | awk -F/ '{print $3}'`
       scancentral package -o sourcecode.zip --build-tool mvn
       java -jar /opt/Fortify/FodUpload/FoDUpload.jar -ac $$FOD_USER $$FOD_PWD -rid $$FOD_RELEASE_ID -purl $$FOD_BASEURL -aurl $fod_api_url -tc $$FOD_TENANT -z sourcecode.zip -ep 2 -rp 2 -pp 2 
  secretEnv: ['FOD_USER', 'FOD_PWD', 'FOD_TENANT'] 
  env:
    - 'FOD_BASEURL=${_FOD_URL}' 
    - 'FOD_RELEASE_ID=${_FOD_RELEASE_ID}' 
  id: 'fortify-static-scan'
  waitFor: ['build-image-IWAJava']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/fod_pwd/versions/1
    env: 'FOD_PWD'
  - versionName: projects/$PROJECT_ID/secrets/fod_user/versions/1
    env: 'FOD_USER'
  - versionName: projects/$PROJECT_ID/secrets/fod_tenant/versions/1
    env: 'FOD_TENANT'    